name: Bench

on:
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run compute benchmark
        run: cargo bench --bench compute

      - name: Upload Criterion report
        uses: actions/upload-artifact@v4
        with:
          name: criterion-report
          path: target/criterion/**

